### ISSUE TITLE
Error when updating to Foundry Version 11

### ISSUE THREAD

**Issue by vt-tom** [Roger92/metric-ruler-labels#34] opened 2023-05-30 18:56 UTC
Error when updating to Foundry Version 11
![grafik](https://github.com/Roger92/metric-ruler-labels/assets/80099175/90b383e7-df09-406e-8a83-02091c79a4ca)

**Comment by dsakura** [comment] 2023-06-11 18:58
Waiting the update too, many thanks

**Comment by Jensenator360** [comment] 2023-06-13 06:37
Same here! +1

**Comment by Far2Casual** [comment] 2023-06-22 18:34
@Roger92 no plans for a V11 release ? This module saves our lives, we metric lovers, for systems like PF2 :(

**Comment by Roger92** [comment] 2023-06-22 18:58
Heyho, I plan to make it work with V11... but i sadly didnt have much time in the last weeks.

I might have some spare hours this weekend. So i try installing V11 and try to update the module ;)

**Comment by Far2Casual** [comment] 2023-06-23 06:59
Thank you so much :)

**Comment by Far2Casual** [comment] 2023-06-29 06:42
Also, FWIW, the module is actually running fine as-in from what I see (at least, for what I'm using it), so there's maybe not that much to do outside of declaring it compatible with V11 already. Even it's integration with Drag Ruler is working. 
![image](https://github.com/Roger92/metric-ruler-labels/assets/63196064/a89c9f08-6e3a-4d18-b638-59de634658a2)

**Comment by Roger92** [comment] 2023-06-29 12:27
Yep also could reproduce that on sunday... i get the same error... will update the manifest today and let you know it it worked :)

SORRY for the delay

**Comment by Roger92** [comment] 2023-06-29 12:50
@Far2Casual @vt-tom @Jensenator360  @dsakura  Alrighty... should work again.

Let me know if it works on your end too. 3.1.7 is the newest version :) And thx again vor using my module. Always nice to hear that it helps someone <3

**Comment by Far2Casual** [comment] 2023-06-29 14:08
Sir, you have nothing to apologize for, thank you !

I know a lot of non-US players of Pathfinder 2 players use your module. The PF2 system implements a lot of distance automation but only supports feet and maps in feet, which is really annoying the 95% of the population that use the metric system. This module helps a ton for those cases, so big up !

**Comment by Roger92** [comment] 2023-11-05 19:31
Since nobody complained ... i guess it was fixed with the last version. If not open another issue :)

**Closed by Roger92** 2023-11-05 19:31 UTC
Labels: bug
